Repository AY2021S2-CS2103T-W13-3/tp, pull requests merged in 2021-04, with the labels that each got.

#171 Fix find by tag
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
Labels: severity.High, type.Bug

#173 Fix find by tag
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/TagsMatchKeywordPredicate.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
Labels: severity.High, type.Bug

#176 Add find by child
  LICENSE
  docs/DeveloperGuide.md
  docs/tutorials/AddRemark.md
  docs/tutorials/RemovingFields.md
  docs/tutorials/TracingCode.md
  src/main/java/seedu/address/logic/commands/EditAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/FindAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/FindAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/Address.java
  src/main/java/seedu/address/model/Name.java
  src/main/java/seedu/address/model/appointment/predicate/ApptAddressContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/appointment/predicate/ApptAnyContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/appointment/predicate/ApptContactsContainKeywordsPredicate.java
  src/main/java/seedu/address/model/appointment/predicate/ApptDateContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/appointment/predicate/ApptFieldContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/appointment/predicate/ApptNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/appointment/predicate/ApptTagsContainKeywordsPredicate.java
  src/main/java/seedu/address/model/contact/Contact.java
  src/main/java/seedu/address/model/contact/Email.java
  src/main/java/seedu/address/model/contact/Favourite.java
  src/main/java/seedu/address/model/contact/Phone.java
  src/main/java/seedu/address/model/contact/exceptions/ContactNotFoundException.java
  src/main/java/seedu/address/model/contact/predicate/AddressContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/contact/predicate/AnyContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/contact/predicate/EmailContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/contact/predicate/FieldContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/contact/predicate/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/contact/predicate/PhoneContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/contact/predicate/TagsMatchKeywordPredicate.java
  src/main/java/seedu/address/storage/JsonAdaptedAppointment.java
  src/main/resources/view/HelpWindow.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddAppointmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParentPalParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/contact/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/contact/TagsMatchKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/ContactBuilder.java
  src/test/java/seedu/address/testutil/EditContactDescriptorBuilder.java
Labels: priority.High, type.Enhancement

#183 Update name of Appilcation
  README.md
  docs/UserGuide.md
  docs/_config.yml
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ThemeCommand.java
Labels: priority.High, type.Task

#185 Update README.md
  README.md
Labels: severity.VeryLow, type.Task

#187 Fix find by tag
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: severity.High, type.Bug

#270 Bug fixes
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/FindAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
Labels: type.Bug

#344 Fix check in DateTime that prevents Appointment data from building
  src/main/java/seedu/address/model/appointment/DateTime.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: severity.High, type.Bug

#345 Fix check in DateTime that prevents Appointment data from building
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: severity.High, type.Bug
